### ISSUE TITLE
Requirement for Unshipped Orders Bulk Invoice Downloader

### ISSUE THREAD

**Issue by JashuvaBLumaple** [daintree2016/Tools-related-Issues#15]
Dear IT Team,
@daintree2016/it-services

We need a tool similar to the one requested by Mohan in Case #14 for bulk invoice downloading. The tool should allow us to download invoices for unshipped orders in bulk to confirm the last dates in Blue-dart.

Currently, we handle this manually for each order, which is time-consuming and affects our productivity. Implementing this tool will help us improve our operations by reducing time consumption.

@daintree2016/fulfilment 

Thanks

**Comment by raj7032** [comment]
Hi Jashuva,
Thanks for reaching out, sure I consider your request and one of our team
members will contact you shortly.

--Rajkumar

**Comment by raj7032** [comment]
the update or follow up from the team is pending due to account deactivation, they said
