### ISSUE TITLE
Shopify - Create bulk upload program

### ISSUE THREAD

**Issue by srikanth-peach** [daintree2016/Tools-related-Issues#2]
In shopify we are uploading each product manually. so we want automation program for this shopify bulk upload file.
![1](https://github.com/user-attachments/assets/8325e03b-cacf-40ba-aa48-d84c6263018d)

**Comment by NavyaThotapalli** [comment]
Hi srikanth,
Thank you for reaching out ,We have successfully completed the Shopify bulk upload automation tool and handed it over to the team. 
If you need any further assistance, feel free to reach out.

Thank you
Navya
