### ISSUE TITLE
FBA -stock issue

### ISSUE THREAD

**Issue by abraham-peach** [daintree2016/Tools-related-Issues#4]
Hi Raj , 
Can you please provide the FBA uploading template for PUID's

**Comment by raj7032** [comment]
Hi Abraham,
Thanks for reaching out, I have added the update that you have requested in WIM website
Now you can upload and confirm FBA Order ids and manage them separately.

**Comment by abraham-peach** [comment]
Okay, thanks Raj.
Regards
Abraham
Peach Imports LLP
Warehouse Management

**Comment by raj7032** [comment]
we are closing this issue since it's already been answered
