### ISSUE TITLE
WIM required for Doveberry

### ISSUE THREAD

**Issue by abraham-peach** [daintree2016/Tools-related-Issues#7]
Hi Raj,
We are required to add in the shipment verification links for Doveberry as per like peach blumaple inbound and outbound.  Can you please make them as per Blumaple WIM activities for Doveberry stock Warehouse Inventory Management? I hope inventory socks with WIM have been managed clearly.

**Comment by raj7032** [comment]
@daintree2016/it-services 
Hi Abraham,
Thanks for reaching out, sure will create the new WIM for doveberry as requested, and you will get the update shortly.
--Rajkumar

**Comment by raj7032** [comment]
@daintree2016/it-services 
Hi Abraham,
New WIM website for Doveberry is ready and made live for usage, check by running some queries with some sample data and let us know for an more updates.

**Comment by abraham-peach** [comment]
@daintree2016/it-services
Hi Raj, Thanks for the update, we have checked and uploaded data to Doveberry WIM and stock data is successfully added to the WIW all working is fine.
