### ISSUE TITLE
"Issue with Buybox_BM_V0 Tool - Expired LWA Secret Token"- Buybox_BM_V0 

### ISSUE THREAD

**Issue by JashuvaBLumaple** [daintree2016/Tools-related-Issues#8]
![Screenshot 2024-09-27 105909](https://github.com/user-attachments/assets/7e1fefe7-e9e8-44f0-9f0a-41b7145c61db)

Dear IT Team,
@daintree2016/it-services 

I'm writing to report two issues we have encountered with our tools:

Buybox_BM_V0: The tool is not working, and it shows the following error message:
"The LWA secret token you provided has expired."
This issue appears to be specific to Buybox_BM_V0.

Live Orders Tracking: When we open the program, the terminal window closes automatically, preventing us from using the tool.

Could you kindly look into these issues and assist in resolving them at your earliest convenience? Your support is much appreciated, as this is affecting our operations.

Thanks

**Comment by raj7032** [comment]
Hi Jasuva,
Thanks for reaching out, looks like the issue is with API credentials of
your seller central which expired recently.
sure our team will fix the issue ASAP and get back to you shortly.

-Rajkumar

**Comment by sarikalohit** [comment]
Hi jashuva,
The issues you have mentioned are resolved please check now and get back to us.
Thank you,
Lohit.

**Comment by JashuvaBLumaple** [comment]
Hi Lohit,

Thank you for the quick resolution. I've checked the tools, and they are now working perfectly.

Appreciate your support!
